### ISSUE TITLE
Add Configuration Installer

### ISSUE THREAD

**Issue by davidbarratt** [drupal-composer/drupal-packagist#23]
I noticed that this module:
https://www.drupal.org/project/config_installer
is missing from Drupal Packagist.

Can it be added? Why would it be missing?

**Comment by webflo** [comment]
I think drupal-parse-composer does not detect D8 install profiles. We have to fix this.

**Comment by webflo** [comment]
Found the issue. We have to parse

https://www.drupal.org/project/project_distribution/index and https://www.drupal.org/project/project_theme/index

**Comment by davidbarratt** [comment]
so something like this?
https://www.drupal.org/api-d7/node.json?type=project_distribution

**Comment by webflo** [comment]
We have a console command to parse this every few ours. We use the https://www.drupal.org/project/project_module/index because everything is on one page :)

Please add the urls to https://github.com/drupal-composer/drupal-packagist/blob/master/src/Packagist/WebBundle/Command/DrupalOrgModuleIndexParserCommand.php

**Comment by webflo** [comment]
Fixed with eb1ae27. Config installer is available http://packagist.drupal-composer.org/packages/drupal/config_installer
