### ISSUE TITLE
Mandrill depends on libraries: >=7.2.x-dev in packagist, but not in its .info file

### ISSUE THREAD

**Issue by pbuyle** [drupal-composer/drupal-packagist#44]
As visible on https://packagist.drupal-composer.org/packages/drupal/mandrill, the drupal/mandrill package depends on libraries: >=7.2.x-dev. But according to the [matching info file](http://cgit.drupalcode.org/mandrill/tree/mandrill.info?h=7.x-2.2), it should depends on libraries >= 7.2.x (ie. no need for -dev).

As a workaround, we use an inline alias alias to trick composer:

```
  "require": {
    "drupal/libraries": "7.2.2 as 7.2.x-dev",
    "drupal/mandrill": "7.2.2"
  }
```

**Comment by webflo** [comment]
Sorry, this got our of my slipped out of my radar last year. I take a look tomorrow.

**Comment by bangpound** [comment]
Thanks for the workaround @pbuyle!

**Comment by dsdobrzynski** [comment]
This actually is a larger issue, as the Information added by Drupal.org packaging script (including version) is missing from the .info(.yml) file. This means that any module that sets a version constraint on a dependency will not be able to be enabled. Rather than a workaround, I think we should fix the underlying issue.

@webflo Any update on this or eta?

**Comment by webflo** [comment]
No sorry, Drupal Packagist won't receive any bugfixes anymore.
